.TH IC 1
.SH NAME
ic \- input contains

.SH SYNOPSIS
ic REGEX

.SH DESCRIPTION
ic returns 0 (true) if it's input contains REGEX, and
returns 1 (false) if it encounters EOF and didn't find
STR in any line.

.SH EXAMPLES
.PP
.fi
.RS
$ ic test </dev/urandom
.RE
.fi
reads from /dev/urandom until it finds the string test.
test.
.PP
.fi
.RS
$ ps -A | ic rlwrap
.RE
.fi
returns true if a rlwrap process is running and false otherwise.

.SH STATUS
0 when the string was found in the input, 1 if not, and 255 when the
usage was printed.

.SH BUGS
Using ic in pipes does not really work well, since results of pipes
can't be examined properly on unix.
.br
Possible solution: use plan9.
.P
ic can be easily written in any language, so why choose myrddin?
But then again-why not?

.SH "SEE ALSO"
.IR grep(1)
does the same thing, faster.

.SH AUTHOR
He can be reached at pranomestro@gmail.com
