.TH IC 1
.SH NAME
ic \- input contains

.SH SYNOPSIS
ic STR

.SH DESCRIPTION
ic returns 0 (true) if it's input contains STR, and
returns 1 (false) if it encounters EOF and didn't find
STR in any line.

.SH EXAMPLE
.TP
.B ic test </dev/urandom
reads from /dev/urandom until it finds the string test
test.
.TP
.B ps -A | ic rlwrap
returns true if a rlwrap process is running and false otherwise.

.SH BUGS
Using ic in pipes does not really work well, since results of
pipes can't be examined properly. Possible solution: let it print
"yes" or "no" if the string was found or not.
.TP
ic does not support regular expressions (yet).
.TP
ic can be easily written in any language, so why choose an unknown one?

.SH AUTHOR
He can be reached at a.regenfuss@gmx.de
