.Dd May 11, 2017
.Dt IC 1
.Os

.Sh NAME
.Nm ic
.Nd input contains

.Sh SYNOPSIS
.Nm
.Ar regex

.Sh DESCRIPTION
.Nm
checks checks if its input contains
.Ar regex .
This is indicated by the return value.

.Sh EXAMPLES
Read from /dev/urandom util the string test is found:
.Pp
.Dl $ ic test </dev/urandom
.Dl output of teh command
.Pp
Return true if a rlwrap process is running, false otherwise:
.Pp
.Dl $ ps -A | ic rlwrap

.Sh EXIT STATUS
If the input contains
.Ar regex ,
0 is returned, if EOF is encountered before finding
.Ar regex ,
.Nm
returns 1. When not given any arguments,
.Nm
exits with 255.

.Sh BUGS
Exit values of pipes can't be properly examined on unix,
which makes it hard to determine whether ic or another command
failed. Possible fix: use plan9.

.Sh SEE ALSO
.Xr grep 1
does the same thing, faster,
.Xr rlwrap 1 ,
.Xr ps 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.de
